### ISSUE TITLE
Dummy Anleitung

### ISSUE THREAD

**Issue by mutsch75** [ThKls/Wallbox-Test#1]
Hi,
docker hab ich auf dem pi bereits installiert, wie komme ich jetzt von dem yaml file zum fertigen container.
Zudem hab ich den USR-TCP232-304 muss ich den adapter noch mit socat zu einem localen device machen ??

**Comment by mutsch75** [comment]
Ok container hab ich hinbekommen :-) hab zudem noch über socat ein device eingerichtet.
 sudo socat pty,link=/dev/virtualcom12,raw tcp:192.168.178.143:502
 Aber leider kommen keine Daten an, hab AG(M)B mit den  unteren 3 Anschlüssen verbunden (RFID) 
 
![image](https://user-images.githubusercontent.com/80944912/115050597-312da200-9edc-11eb-9703-f38571e7aa21.png)

**Comment by mutsch75** [comment]
Gerade noch folgenden Eintrag gefunden, 
app_1  | (node:21) UnhandledPromiseRejectionWarning: Error: Error: Input/output error, cannot open /dev/ttyModBus

Eintrag im yml:       - /dev/virtualcom12:/dev/ttyModBus

**Comment by ThKls** [comment]
Die Fehlermeldung bedeutet, dass die serielle Schnittstelle nicht initialisiert werden kann. Das Programm erwartet eine serielle Schnittstelle, deren Parameter (Baudrate etc.) gesetzt werden können. Schon das klappt nicht.
