### ISSUE TITLE
Make run

### ISSUE THREAD

**Issue by Patrick-Walther** [ThKls/Wallbox-Test#2]
Hallo,

Wie installiere/nutze ich den make befehl?

**Comment by ThKls** [comment]
> Hallo,
> 
> 
> 
> Wie installiere/nutze ich den make befehl? 

Hi,

make ist im gleichnamigen Paket. Also als root:
```
apt install make
```

**Comment by Patrick-Walther** [comment]
Frohes neues Jahr. Vielen Dank! Hat wunderbar funktioniert.
